# Conclusion

In conclusion, we sought out to answer some fundamental exploratory questions about COVID spread in New York State. For example, we asked: "How many waves of COVID did New York experience and when did they occur?" and "What is the nature of the geographic spread of COVID in New York, do nearby counties tend to have more correlated cases than ones which are further away?". We found that the appropriate metric to use for such answers was the percentage of positive test cases each day, since it inherently normalises for number of tests taken. This is not true for the raw number of positive tests, because it was strongly linked to number of tests taken (and is therefore biased towards counties with higher numbers of tests). We found that beyond the initial COVID outbreak, there were 2 main waves: One mild which occurred at the end of 2020, and another more severe wave which spiked drastically around the 2022 new year. We also noted that within New York state, COVID spread roughly locally. That is, counties closer together tended to have more temporally-related case spread, whereas counties that are further apart were less correlated in this regard.

For further exploration of this topic, we may like to consider other states and create similar plots examining counties across the whole country. This question would be very interesting, but would require significantly more effort due to the nature of different data sources required for each state.